# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-neon
    container_name: selenium-hub
    networks: ['selenium-grid']
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome-debug:3.141.59-neon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    ports:
          - "5555:5555"
          - "5556:5900"
# pwd to VNC Server : secret
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
    networks: ['selenium-grid']
networks: {selenium-grid: {}}